---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: web
    run_list:
      - recipe[web::default]
    attributes:
  - name: app
    run_list:
      - recipe[app::default]
    attributes:
